export const DISHES_LOADING='DISHES_LOADING';
export const ADD_DISHES='ADD_DISHES';
export const DISHES_FAILED='DISHES_FAILED';

export const SLIDERIMAGE_LOADING='SLIDERIMAGE_LOADING';
export const ADD_SLIDERIMAGE='ADD_SLIDERIMAGE';
export const SLIDERIMAGE_FAILED='SLIDERIMAGE_FAILED';

export const ADD_COMMENTS='ADD_COMMENTS';
export const POST_COMMENTS='POST_COMMENTS';
export const COMMENTS_FAILED='COMMENTS_FAILED';

export const ADD_CART='ADD_CART';
export const POST_CART='POST_CART';
export const CART_FAILED='CART_FAILED';
export const CART_LOADING='CART_LOADING';
export const CART_DELETE='CART_DELETE';
export const CART_EMPTY='CART_EMPTY';

export const ADD_LEADERS='ADD_LEADERS';
export const LEADERS_FAILED='LEADERS_FAILED';
export const LEADERS_LOADING='LEADERS_LOADING';

export const LOGIN_DONE='LOGIN_DONE';
export const LOGIN_LOADING='LOGIN_LOADING';
export const LOGIN_FAILED='LOGIN_FAILED';


export const REGISTER_DONE=' REGISTER_DONE';
export const  REGISTER_LOADING=' REGISTER_LOADING';
export const  REGISTER_FAILED=' REGISTER_FAILED';

export const LOGOUT_DONE='LOGOUT_DONE';

